### ISSUE TITLE
Setting a path to `flow` bin?

### ISSUE THREAD

**Issue by saadq** [steelbrain/flow-ide#100]
Is there a way to set a path to the `flow` bin you want to use? I was trying to contribute to `flow`, so I would need to use the compiled, built `flow` binary instead of using one that I `npm install`. Is there a way I can set the compiled `flow` binary that is in some other directory to be the one used by `flow-ide`? I tried searching the settings for the package, although I don't think there is any configuration available there.

**Comment by steelbrain** [comment]
If you don't have any flow installed locally, you could set the `executablePath` config.

If you do, you can just override it with this in the project root
```
ln -s /path/to/my/flow ./node_modules/.bin/flow
```

**Comment by saadq** [comment]
I'll go with the symlink option, thanks for the quick reply.
