### ISSUE TITLE
Add Getting Started section to README

### ISSUE THREAD

**Issue by nwshane** [steelbrain/flow-ide#104]
I'm trying to setup this package, but I can't get it working and there doesn't seem to be documentation on how to get started. I installed the plugin in atom, opened my flow project (with a valid .flowconfig), and I'm not getting any flow feedback. Also tried adding `./node_modules/.bin/flow` as Executable Path in Settings but no luck.

Can someone lay out the steps for setting up this package?

**Comment by steelbrain** [comment]
Hi @nwshane 

You should reset that executable path configuration, it's not necessary. You should also see a prompt asking you to install the `linter` and `linter-ui-default` packages, install them or enable if you haven't already.

That should be it, saving a file should give you the errors/issues for the entire flow project

**Comment by nwshane** [comment]
@steelbrain Oh wow, my linter was disabled from when I was using Nuclide before. Sorry about that and thanks for the help.
