### ISSUE TITLE
ReferenceError: err is not defined

### ISSUE THREAD

**Issue by n1k0** [steelbrain/flow-ide#12]
Atom 1.8.0, Linux 64. Just installed the package, opened a file with valid flow annotations, got this: 

![](http://i.imgur.com/Q2htOYt.png)

Don't much know what to do next :)

**Comment by spalger** [comment]
Oops, my bad, fix incoming

**Comment by spalger** [comment]
@n1k0 in the meantime I suggest you install flow locally with `npm install --save-dev flow-bin`
