### ISSUE TITLE
Relative path flow? ./node_modules/.bin/flow

### ISSUE THREAD

**Issue by schoettler** [steelbrain/flow-ide#125]
The plugin seems to have a problem finding `./node_modules/.bin/flow` to use the project's flow. This would be ideal as some projects have different flow versions locally

**Comment by lloiser** [comment]
https://github.com/facebook/flow#installing-flow-per-project

> The recommended way to install Flow is via the [flow-bin](https://www.npmjs.com/package/flow-bin) npm package

**Comment by schoettler** [comment]
For anyone having a similar issue, solved it by simply removing the flow path in the settings, defaults to the local `flow-bin` installation as expected
