### ISSUE TITLE
[Linter] Error running Flow IDE Coverage Error: Unhandled exception

### ISSUE THREAD

**Issue by doberkofler** [steelbrain/flow-ide#130]
In the last couple of days I see the following error message when starting Atom:

```
[Linter] Error running Flow IDE Coverage Error: Unhandled exception: Unix.Unix_error(Unix.EPIPE, "read", "")
Raised by primitive operation at file "unix.ml", line 191, characters 7-33
Called from file ".\hack\utils\marshal_tools.ml", line 176, characters 4-89
Called from file ".\src\monitor\flowServerMonitorDaemon.ml", line 55, characters 4-71
Called from file ".\src\flow.ml", line 82, characters 6-34
Called from file ".\src\flow.ml", line 120, characters 4-21

Could not start Flow server!
    at ChildProcess.<anonymous> (C:\Users\doberkofler.LBITS\.atom\packages\flow-ide\node_modules\sb-exec\lib\index.js:56:20)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:885:16)
    at Socket.<anonymous> (internal/child_process.js:334:11)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at Pipe._handle.close [as _onclose] (net.js:501:12)
```

I'm using:

Atom    : 1.24.0
Electron: 1.6.16
Chrome  : 56.0.2924.87
Node    : 7.4.0

Community Packages
├── busy-signal@1.4.3
├── file-icons@2.1.16
├── flow-ide@1.10.0
├── gist-it@0.9.2
├── hyperclick@0.1.5
├── intentions@1.1.5
├── language-oracle@1.9.0
├── linter@2.2.0
├── linter-eslint@8.4.1
├── linter-stylelint@4.2.0 (disabled)
├── linter-stylint@2.2.8
├── linter-ui-default@1.6.10
├── platformio-ide-terminal@2.8.0
├── project-manager@3.3.5
├── split-diff@1.5.2
├── Stylus@3.1.1
├── Sublime-Style-Column-Selection@1.7.4
├── sync-settings@0.8.3
└── teletype@0.8.0 (disabled)

I actually reported this problem a while ago and it was related to a timeout values that "you" somehow fixed.

**Comment by steelbrain** [comment]
Hi @doberkofler

It's a unix pipe read error this time, coming not from Atom or any of it's packages but from flowtype itself. Flow is not stable on windows so you're unfortunately gonna have to come across errors such as these :(

You can try reporting this on the official flowtype repo and the authors might fix it, but there's nothing I can do from this package

Thanks for taking the time to report this, thanks!
