### ISSUE TITLE
[config] Exclude __tests__ paths or .test.js files from type checking

### ISSUE THREAD

**Issue by YUzhva** [steelbrain/flow-ide#131]
Is there any way to do that?

Is that possible to do as the feature for config?

**Comment by lloiser** [comment]
`flow` itself provides an [`[ignore]`](https://flow.org/en/docs/config/ignore/) section in the `.flowconfig`.

**Comment by YUzhva** [comment]
It looks like `flow` doesn't configure properly in my project.

Because I already added `__tests__` folders to `.flowconfig` file like:
```javascript
[ignore]
...
.*/__tests__/.*
```

When I'm running `yarn flow` command - there is always 0 errors in console, but there could and issues (highlighted by `flow-ide`) at file + `flow-ide` ignoring `.flowconfig` file...

I'm closing this issues - going try to reconfigure `flow` for the project...
