### ISSUE TITLE
Datatip displays plain HTML

### ISSUE THREAD

**Issue by MrLoh** [steelbrain/flow-ide#139]
Probably I'm missing some setting, but I can't find any hint in the documentation. I have Atom-IDE installed and in the tooltips I get shown this plain HTML which is completely unreadable. Any idea what the issue is? 

<img width="943" alt="screen shot 2018-05-02 at 12 22 40" src="https://user-images.githubusercontent.com/1285032/39518535-8edcd7f4-4e03-11e8-92f1-48b8824d11cd.png">

**Comment by steelbrain** [comment]
Hi @MrLoh 

This is an incompatibility issue with `atom-ide-ui`. They do not fully support the Atom Linter API v2. You should open an issue with them asking them to support this

**Comment by lloiser** [comment]
I have been working on it for some time now, but it has not been merged yet... https://github.com/facebook-atom/atom-ide-ui/pull/164

**Comment by IanVS** [comment]
I guess this can be closed now, right?
