### ISSUE TITLE
ignoreExitCode and do not throwOnStdErr on exec flow.exe

### ISSUE THREAD

**Issue by LastLeaf** [steelbrain/flow-ide#16]
I tried to build a Windows version of Flow.
It works, but throws something to stderr but I cannot figure out why.
Due to this, flow-ide shows an error and interrupted linting.

I tried to set `throwOnStdErr` to `false` in exec options, and it works OK.
The autocompletion seems to work with this option and `ignoreExitCode: true`.
The modified code is in my fork currently. But I have not tested it in other platforms.

**Comment by steelbrain** [comment]
This is actually a rare case, it works fine without those options on linux and mac. When flow on windows reaches stable, it won't need that for windows either.

Until then IMO it's fair to manually set those options, let me know what you think?

**Comment by LastLeaf** [comment]
Agree.

**Comment by steelbrain** [comment]
Closing based on discussion above. Feel free to continue discussing
