### ISSUE TITLE
flow-ide should handle "flow is rechecking" response

### ISSUE THREAD

**Issue by Gozala** [steelbrain/flow-ide#20]
In a larger projects flow tend to take time to recheck printing 'flow is rechecking' message before it's finished. In such projects **flow-ide** is pretty much unusable resulting in this:

<img width="472" alt="screen shot 2016-07-28 at 10 11 06 am" src="https://cloud.githubusercontent.com/assets/21236/17222151/b8c9f4d2-54ab-11e6-803c-51d576372c55.png">

I would expect it to handle such cases gracefully.

**Comment by steelbrain** [comment]
Sounds fair

**Comment by steelbrain** [comment]
Fixed in v1.1.4
