### ISSUE TITLE
Jump to declarations

### ISSUE THREAD

**Issue by steelbrain** [steelbrain/flow-ide#24]
Just like the title says. Making an issue so I don't forget

**Comment by ericjohney** [comment]
Hi Brian! Is it ok if give this issue a try in the next few days?

**Comment by steelbrain** [comment]
@ericjohney This is actually already implemented in `declarations-js` Atom package :)

**Comment by ericjohney** [comment]
oh nice, i'm gointo to have to just go through and install all your packages. 

Anything I can help with?

**Comment by steelbrain** [comment]
@ericjohney That is so very nice of you :) I could surely use some help with [`linter-ui-default`](https://github.com/steelbrain/linter-ui-default/) and [`react-table`](https://github.com/steelbrain/react-table) (it needs resize support)

Closing this particular bug as it's already implemented in my other package `declarations-js`

**Comment by ericjohney** [comment]
will do! i'll go check those projects out
