### ISSUE TITLE
1.1.6 update breaks the linter.

### ISSUE THREAD

**Issue by AriaFallah** [steelbrain/flow-ide#28]
Given the following code:

```js
// @flow

flowIDEBroke('')

function flowIDEBroke(x: number): number {
  return x
}
```

With `flow-ide@1.1.6` there is no error message, but running flow from the terminal shows:

```java
index.js:3
  3: flowIDEBroke('')
     ^^^^^^^^^^^^^^^^ function call
  3: flowIDEBroke('')
                  ^^ string. This type is incompatible with
  5: function flowIDEBroke(x: number): number {
                              ^^^^^^ number


Found 1 error
```

---

If you revert using

```bash
apm install flow-ide@1.1.5
```

the errors in the editor pop back up.

**Comment by steelbrain** [comment]
The [diff](https://github.com/steelbrain/flow-ide/compare/v1.1.5...master) doesn't show much. Can I see this on teamviewer or something? (PM me the details on slack)

**Comment by AriaFallah** [comment]
Perhaps it's the change to linter `v7 -> v8`? Wouldn't that be a breaking change that could cause the problem?

Here's a video for you of the problem: https://streamable.com/r71o

**Comment by steelbrain** [comment]
Do you have `flow` executable in the project? Is it possible that you have more than one `flow` executables in your `$PATH`? (check all the dirs in your `$PATH` to make sure)

**Comment by AriaFallah** [comment]
I only have one instance of flow under `/usr/local/bin/flow` that I installed using homebrew.

**Comment by steelbrain** [comment]
Have you installed `flow-bin` via npm in the project?

**Comment by AriaFallah** [comment]
Nope. I'm guessing I should have that?

**Comment by steelbrain** [comment]
Can you try installing that and see if the behavior changes?

**Comment by AriaFallah** [comment]
No difference:

```json
{
  "name": "temp",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "flow": "./node_modules/.bin/flow"
  },
  "keywords": [],
  "author": "",
  "license": "MIT",
  "devDependencies": {
    "flow-bin": "^0.31.1"
  }
}
```

Doing `npm run flow` gave me the expected result.

**Comment by steelbrain** [comment]
LifeProTip: npm scripts already have `./node_modules/.bin` in their `$PATH` so you can just write `flow` and it'll use the local.

I'm gonna try to repro this error locally and post the findings

**Comment by AriaFallah** [comment]
haha I figured but I wanted to 100% sure it was using the version from npm instead of brew.

**Comment by steelbrain** [comment]
Commands I used to repro
```
$ cd /tmp
$ mkdir flow-test
$ cd test
$ echo '{"name": "flow-test"}' > package.json
$ npm install --save-dev flow-bin
$ ./node_modules/.bin/flow init
$ atom .
```

then this
<img src="https://cloud.githubusercontent.com/assets/4278113/18135114/98bf8e58-6f55-11e6-86d9-00bf7cc104b9.png">

**Comment by steelbrain** [comment]
Oopsie found the problem, I had accidentally published from `steelbrain/linter-next` branch instead of `master` 😛 Fixing

**Comment by AriaFallah** [comment]
@steelbrain lol...

Also unrelated. How did you make your linter UI look like that?

**Comment by steelbrain** [comment]
Fixed in v1.1.7

It's the unreleased linter UI. If you wanna be the early bird, installation instructions are in [linter-ui-default README](https://github.com/steelbrain/linter-ui-default#installation)

**Comment by AriaFallah** [comment]
@steelbrain 

Did you ever publish v1.1.7

**Comment by steelbrain** [comment]
I did, APM even created a git tag on this repo but didn't publish :\
