### ISSUE TITLE
errors not showing up inline

### ISSUE THREAD

**Issue by gnoff** [steelbrain/flow-ide#29]
As of today (after some fairy heavy refactoring) inline linter errors stopped showing up. I still see the warnings in the issues shown at the bottom of the window and I can confirm that these issues match the issues found when manually running flow and they do update if I intentionally introduce new errors.

I still see linter-eslint errors inline so I don't think the issue is affecting all of my linter implementations.

On version 1.1.5, tried 1.1.6 but nothing worked then

Flow 0.31 if it matters. Flow server is running if that also matters

**Comment by steelbrain** [comment]
See explanation in another bug, https://github.com/steelbrain/flow-ide/issues/28#issuecomment-244519989
APM was having hiccups back when I published the updates
