### ISSUE TITLE
Don't list autocomplete suggestions after a comma.

### ISSUE THREAD

**Issue by AriaFallah** [steelbrain/flow-ide#3]
Leads to a lot of accidental completions when populating an object's properties:

```javascript
{
  x: 1,
  y: 2, // <---- autocompletes when I press enter for a new line
}
```

https://gfycat.com/RewardingTameIberiannase

**Comment by AriaFallah** [comment]
@steelbrain Awesome! You're so productive haha.

**Comment by steelbrain** [comment]
:bow:
