### ISSUE TITLE
Add support for flow traces

### ISSUE THREAD

**Issue by zerkalica** [steelbrain/flow-ide#31]
```js
// @flow

interface Props {
    p: number;
}

function Component(props: Props) { // <---- atom show error only here
    return <div>{props.p}</div>
}

function Component2(props: Props) {
    return <div><Component /></div>
}
```

```bash
flow check
src/t.js:7
  7: function Component(props: Props) {
                               ^^^^^ property `p` of Props. Property not found in
 12:     return <div><Component /></div>
                     ^^^^^^^^^^^^^ props of React element `Component`
```

**Comment by steelbrain** [comment]
You might wanna redirect this to https://github.com/facebook/flow instead :)

**Comment by zerkalica** [comment]
Why? flow check shows this error: 12:     return <div><Component /></div>,
Atom - not.

**Comment by steelbrain** [comment]
Well actually, that's just one error and the second one is a trace to that error, I could add support for traces in this package if that's what you meant

**Comment by zerkalica** [comment]
Yes, thankyou =)

**Comment by Erid** [comment]
Not sure if related, but having the ability to click on the trace is pretty good too, linter-flow does this pretty well, if for example I had an issue related to a NodeJS internal it would send me to flow's type information, for example:

![image](https://cloud.githubusercontent.com/assets/703220/18803790/c0a456fc-81b0-11e6-952e-5276147ee997.png)

Clicking the trace reference opens up the file that has the declaration (which in this case is a file from flow):
![image](https://cloud.githubusercontent.com/assets/703220/18803802/e4331b80-81b0-11e6-9781-ffad845c73ff.png)

**Comment by steelbrain** [comment]
Thanks for reminding me about this @Erid. I'll fix it this week (hopefully)

**Comment by steelbrain** [comment]
Hey, I just confirmed, we already have support for flow traces

**Comment by Erid** [comment]
Nice, it's working as expected :+1:
