### ISSUE TITLE
Unable to find files when using custom Webpack resolver.

### ISSUE THREAD

**Issue by jckdrpr** [steelbrain/flow-ide#32]
Hi I was using this plugin but when using non-relative paths as disscussed in here http://moduscreate.com/es6-es2015-import-no-relative-path-webpack/, the flow-ide can't seem to find the module. (i.e. throws a warning required module not found)

**Comment by steelbrain** [comment]
That's actually a flow thing, not a flow-ide thing :)
The repo you should open this at is https://github.com/facebook/flow
