### ISSUE TITLE
Joining efforts

### ISSUE THREAD

**Issue by ctrlplusb** [steelbrain/flow-ide#40]
I see there is another plugin trying to accomplish the same thing.

https://github.com/lukehoban/atom-ide-flow

Do you think it is worth approaching the author to combine your efforts into a single repo.  Shared efforts and merged communities. x

**Comment by steelbrain** [comment]
Hi @ctrlplusb 

Thank you for your suggestion, while I am 100% in favor of combining efforts and working together a single goal, that repo is no longer maintained, therefore merging with it will serve no benefit to this package.

We can however request the author of that package to depreciate his outdated package in favor of his, which tbh is pretty unlikely to happen :)

**Comment by ctrlplusb** [comment]
Hi @steelbrain 

Ah, that's fair enough.  

Thanks for this awesome plugin.  I really appreciate it.
