### ISSUE TITLE
When does flow-ide stop the flow server?

### ISSUE THREAD

**Issue by qimingweng** [steelbrain/flow-ide#50]
I could be completely wrong but I have a small suspicion that flow servers are spawned and never deleted. My CPU runs like crazy after opening and closing a few atom projects.

Of course, atom has never been the best editor in terms of performance but kind of curious about this.

Otherwise this is really good haha. Favourite flow IDE.

**Comment by steelbrain** [comment]
Yes, your suspicion is correct. Flow servers are spawned and never terminated. Though they mostly take very little resources and are killed on restart anyway so I didn't think it was important.

I don't mind doing it though :)

**Comment by wtgtybhertgeghgtwtg** [comment]
Would you like a PR on this?  Would it be a matter of adding a finally to the try-catch blocks around `exec`?

**Comment by steelbrain** [comment]
Thank You so much @wtgtybhertgeghgtwtg for offering. Thank you all for being so patient. I've added support for this in #58. It'll be a part of the next update that'll go live in a few hours

**Comment by shodanuk** [comment]
Sorry to revisit this but just to confirm: should Flow server instances be killed when Atom exits, when using flow-ide?

I'm currently seeing multiple instances of flow remaining after Atom closes, sometimes as many as 7. These are instances of flow provided by locally installed flow-bin which flow-ide seems to be detecting automatically. The versions of what I'm running are as follows:

- atom 1.15
- flow-ide 1.4.1
- flow-bin 0.42.0

**Comment by chanceeakin** [comment]
Currently experiencing unterminated flow watchers/processes as well.

* macOS 10.13.3
* atom 1.25.0
* flow-ide 1.11.0
* flow-bin 0.68.0

**Comment by lloiser** [comment]
The previous implementation was able to detect when flow-ide started a new flow server because flow reported some specific error messages while starting the flow server. At least with flow 0.68.0 (and probably a lot eariler too) this is not the case anymore...

We could easily add an option to flow-ide to stop all flow server that we know of when closing atom. How does this sound @chanceeakin @steelbrain?

**Comment by chanceeakin** [comment]
@lloiser: Sounds like I owe you a beer next time you're in Texas. 👍
