### ISSUE TITLE
Coverage can render NaN%

### ISSUE THREAD

**Issue by stowball** [steelbrain/flow-ide#52]
I put `// @flow` at the top of all my files, so when it's on a file that looks like this:

```js
// @flow
import Table from './Table';
import Table__Row from './Table__Row';
import Table__Cell from './Table__Cell';

export {
    Table,
    Table__Row,
    Table__Cell
};
```

the coverage reports `NaN%`

![image](https://cloud.githubusercontent.com/assets/853552/21205943/134f5562-c2b3-11e6-920c-98e8b128bea4.png)

**Comment by steelbrain** [comment]
Fixed in v1.2.4

**Comment by steelbrain** [comment]
Thanks for the good repro case by the way, awesome bug report 👍

**Comment by stowball** [comment]
\o/

Thank you for the plugin!
