### ISSUE TITLE
Implement showing type on hover similar to ide-haskell

### ISSUE THREAD

**Issue by AriaFallah** [steelbrain/flow-ide#6]
Not sure if this is too big of a reach for flow, but it'd be nice to be able to hover over variables and see what flow thinks their types are.

**Comment by steelbrain** [comment]
Blocked on https://github.com/steelbrain/intentions/issues/15

**Comment by jonathandelgado** [comment]
I'll go ahead and implement this once the tooltips API is added, if you weren't already planning on it!

**Comment by steelbrain** [comment]
@jonathandelgado That sounds wonderful, I would appreciate it very much. Would you like to do it in the intentions package instead? If we do it there, we'll be able to reuse them in not just this package but in a lot of others

**Comment by jonathandelgado** [comment]
@steelbrain Sorry, I think I may have not been clear enough, I don't want to implement the actual tooltip API in the `intentions` package, I think that might be a little over my head time-wise. But once that API has been implemented, I would be happy to utilize it and implement the 'hover over type checking' feature. Again, sorry for the confusion.

**Comment by zaaack** [comment]
How about using [atom-ide-ui](https://github.com/facebook/nuclide/tree/master/modules/atom-ide-ui)'s data-tips feature to implement type hint? Since it looks like [atom-languageclient](https://github.com/atom/atom-languageclient)'s official API.

**Comment by johnhaley81** [comment]
@steelbrain would https://github.com/steelbrain/flow-ide/issues/6#issuecomment-315605447 be sufficient or are you still wanting to use https://github.com/steelbrain/intentions/issues/15 ?

Either way I use flow-ide everyday and I love it. I've wanted the feature in this issue for a while now so if there is something I can do to move this along I would be able to give some time to help.

**Comment by lloiser** [comment]
> How about using atom-ide-ui's data-tips

added with #116
