### ISSUE TITLE
Add a config to show warnings

### ISSUE THREAD

**Issue by NameFILIP** [steelbrain/flow-ide#63]
I want to see `code not covered` highlighted with yellow. Is it currently possible with this plugin? If no - it would be very useful to have

**Comment by steelbrain** [comment]
We already show warnings and the description of the bug report doesn't help much. Can you please elaborate your issue or request further?

**Comment by NameFILIP** [comment]
I can see `Flow Coverage: 75%` in the status bar, but I can not see warnings for the parts that are not covered by flow. I can see it in Nuclide, but not with this plugin.
(see https://github.com/facebook/nuclide/issues/870)

**Comment by lloiser** [comment]
Added in [v1.5.0](https://github.com/steelbrain/flow-ide/blob/master/CHANGELOG.md#150)
