### ISSUE TITLE
Autocomplete Across Files

### ISSUE THREAD

**Issue by alflennik** [steelbrain/flow-ide#71]
Autocomplete doesn't work on functions imported like this: `import { validateArgs } from './validate-args'`. 

However if I go to validate-args.js, the autocomplete works great. It knows the types, can autofill the arguments for me.

This is a problem with autocomplete-flow as well, so I came over to try flow-ide to see if it works. Is this a problem with flow itself? I'd really like to see this functionality, it would save me time! Perhaps I'm using the plugin incorrectly. Thanks!

**Comment by steelbrain** [comment]
I think it's a limitation of flow itself, if you want to see autocompletes in a file you have to have a flow config in project root.

If you have a flow config in project root you'll get autocompletes but they won't be deep and would be non-super-accurate, to get accurate autocompletes you have to add the flow pragma in the files you're requiring and in the file you're working in.

Closing as answered but feel free to continue discussing.

**Comment by alflennik** [comment]
Thanks, this helps! Maybe make a note in the readme for confused devs like
me.
