### ISSUE TITLE
Visual Flow Coverage

### ISSUE THREAD

**Issue by awilkins** [steelbrain/flow-ide#72]
Aside from the %age, a very nice feature of Nuclide is showing you with a highlight what code is covered.

https://nuclide.io/docs/languages/flow/#type-coverage

Can I suggest this go on the roadmap? :sweat_smile:

**Comment by steelbrain** [comment]
Sounds good

**Comment by lloiser** [comment]
Are there any preferences how this should look like?

I tried to actually highlight the code ranges in the editor. What do you think?
![image](https://cloud.githubusercontent.com/assets/3003233/26377431/86743e74-4010-11e7-9f4a-30019196456b.png)
(both `this.tooltipDisposable` and `atom.tooltips` are part of 2 code ranges that's why they have a stronger background color)

**Comment by steelbrain** [comment]
Hi @lloiser 

The functionality looks good! I would personally suggest that it doesn't add a special background to it, just the same background that you get when you select some text so it feels natural. But that's just my two cents

**Comment by lloiser** [comment]
Honestly: this feels weird. You won't see any selection that you have within these uncovered ranges.
btw. I actually selected the `Conte` of `this.textContent` on line 50.
![image](https://cloud.githubusercontent.com/assets/3003233/26377877/7899de9c-4012-11e7-88f4-cb80ea66a5de.png)

**Comment by steelbrain** [comment]
Agreed, it does feel weird. Looked a lot better in my imagination 😛 

Do we have any other packages providing visual flow coverage that we can steal the styles from?

**Comment by lloiser** [comment]
Maybe we could use a _single_ linter message/warning saying something like "uncovered flow types" and provide _all_ uncovered locations/ranges for this single message. Users are used to these "squiggly underlines" of the linter already.

**Comment by steelbrain** [comment]
That would actually get real messy when people will hover them. will post in #ui of Atom Slack for suggestions

**Comment by lloiser** [comment]
FYI: visual studio code adds "informational" messages to the "problems" list (aka linter) for each uncovered range.

![image](https://cloud.githubusercontent.com/assets/3003233/26460628/8d86f09c-417a-11e7-8f03-2efd08956d64.png)

**Comment by steelbrain** [comment]
Fair enough, I'm in 👍 of Linter Infos

**Comment by lloiser** [comment]
Added in [v1.5.0](https://github.com/steelbrain/flow-ide/blob/master/CHANGELOG.md#150)
