### ISSUE TITLE
Question : Ability to show JSDOC Documentation in Suggestions

### ISSUE THREAD

**Issue by rwatts3** [steelbrain/flow-ide#79]
Greetings,

First and foremost nice work on this project. 
I am curious if it is possible to show `jsdoc` style documentation in the suggestions ? 
I'm not sure if this would be a `flow-ide` or `flow` type of configuration.

Thank you for your time, 

Ryan

**Comment by steelbrain** [comment]
Hi @rwatts3 

Thank you for your request. `flow-ide` is a mere interface to the underlying [`flow`](https://github.com/facebook/flow) by fb. This issue would be better suited in that repository. Thank You 👍
