### ISSUE TITLE
Limit spawning autocomplete processes

### ISSUE THREAD

**Issue by mjomble** [steelbrain/flow-ide#81]
Every now and then flow-ide puts a lot of strain on my system and I see a ton of `flow autocomplete` processes in Task Manager.

I haven't confirmed this, but my current theory is that when Flow is performing some large computations (sometimes it takes over a minute on my laptop), every autocomplete process will have to wait until this computation is complete. But every new keypress in the editor spawns a new autocomplete process. So this results in a large number of processes which slow down the computer, which probably makes the large Flow computation take even more time, starting a feedback loop of slowness.

If this theory is correct, perhaps a good solution would be to limit the number of autocomplete processes that are spawned? e.g. if there are, say, 5 already running, don't start any new ones until those have completed.

**Comment by steelbrain** [comment]
Hi @mjomble

The way it works is on the first request to a flow project, a flow server is spawned (which is closed when you close Atom), each autocomplete request is then made to that server.

Previously we weren't just disregarding results of old ones in case of multiple invocations but now this package makes sure to properly kill the old processes

**Comment by mjomble** [comment]
Cool, thanks for the quick fix! :)
