### ISSUE TITLE
Missing warning/error

### ISSUE THREAD

**Issue by lloiser** [steelbrain/flow-ide#85]
Given: [https://flow.org/try/#0PTAE...](https://flow.org/try/#0PTAEAEDMBsHsHcBQiAmBTAxtAhgJzaAC4CeADgQApq4DOsAdqALygDeioo92AtmgFygahXAEt6AcwDciAL7JIAV3oZCohqFK5YpAKIBHRdmgAKLTpoAaULEIALahW2krm5wEo2HTqHyFFuIzmLgDawQC6zEwstg64ThZhzuEy8ohKKmoaGLA8pHhoZgCMglS0DNakAEyCAPxldPSe7D6+aP6BbjoGRqakRZVV1gBE3HzD7qnIOfTCmkXMbFy8AqDDAFKwdvTDoLIyM3PVi-SK0NAyiDl5BcWDk4hAA)

This is the output in atom:

![screenshot](https://cloud.githubusercontent.com/assets/3003233/25480991/86fff3a8-2b4b-11e7-8ad6-cfb228bd25f6.png)

This is the output of `flow` on the command line

```
person.js:12
 12:     return propEqual(p1, p2, "name");
                ^^^^^^^^^^^^^^^^^^^^^^^^^ function call
  8:     return props[prop] === otherProps[prop];
                                ^^^^^^^^^^^^^^^^ access of computed property/element. Computed property/element cannot be accessed on possibly null value
  8:     return props[prop] === otherProps[prop];
                                ^^^^^^^^^^ null

person.js:12
 12:     return propEqual(p1, p2, "name");
                ^^^^^^^^^^^^^^^^^^^^^^^^^ function call
  8:     return props[prop] === otherProps[prop];
                                ^^^^^^^^^^^^^^^^ access of computed property/element. Computed property/element cannot be accessed on possibly undefined value
  8:     return props[prop] === otherProps[prop];
                                ^^^^^^^^^^ undefined


Found 2 errors
```

So the output of flow includes one additional line (`12: ...`) that is actually really useful as it points to where the function is called. In a project where this is a helper function that lives somewhere in a `helper.js` this gets a little bit harder to track down the actual errors.

The additional line is also returned in the JSON that is available here: https://github.com/steelbrain/flow-ide/blob/v1.4.2/lib/helpers.js#L38-L54. It's stored on `error.operation`.

**Comment by steelbrain** [comment]
References need a little love, thanks for bringing this to attention

**Comment by lloiser** [comment]
Any ideas how this might look like?

e.g. [nuclide](https://github.com/facebook/nuclide) "tries" to display the same text as in the command line:
![image](https://cloud.githubusercontent.com/assets/3003233/26530905/de29ced2-43de-11e7-8174-abbdef8d9057.png)
I admit, this does not look nice at all but it gives you all the necessary information. It even lets you jump to the 2 different locations.
fyi: the code that creates this output: https://github.com/facebook/nuclide/blob/master/pkg/nuclide-flow-rpc/lib/diagnosticsParser.js

I've also found this piece of code in the flow repo that does pretty much the same: https://github.com/facebook/flow/blob/master/tsrc/flowResult.js

**Comment by steelbrain** [comment]
@lloiser I think our excerpts look nicer. How about we add all this useful into to the `description` property in Linter Messages? I think it would expand when needed (instead of cluttering the UI) and provide people with the info they need

**Comment by lloiser** [comment]
first prototype: 
![image](https://cloud.githubusercontent.com/assets/3003233/26532322/bc36d83c-43fd-11e7-9f3f-2e83d8197062.png)

It looks really ugly because the message is multi line and uses space indentation but the linter-ui just ignores it 😞

**Comment by steelbrain** [comment]
Oh Boy, looks like you've hit https://github.com/steelbrain/linter/issues/1389 😛

**Comment by lloiser** [comment]
second prototype: 
![image](https://cloud.githubusercontent.com/assets/3003233/26561244/0db4a03a-44bd-11e7-85c9-9d4a875ac315.png)

I would love to make this file paths clickable. Unfortunately this is not possible because I have "fenced" everything to get these lines and whitespaces correctly aligned 😭 
Any other ideas? I could try to wrap everything in single inline code blocks instead.

**Comment by steelbrain** [comment]
Looks good. Are you on Atom slack btw? I would be happy to discuss an API that fixes the limitations posed 😛
