### ISSUE TITLE
Setting void as empty "parameter" definition generates an underscore

### ISSUE THREAD

**Issue by lgraziani2712** [steelbrain/flow-ide#86]
Hello, here is the type definition:

![image](https://cloud.githubusercontent.com/assets/15050200/25731660/9f48c1c8-311e-11e7-93d8-1232eef50db8.png)

This is the autocomplete result:

![image](https://cloud.githubusercontent.com/assets/15050200/25731681/bab87d90-311e-11e7-8fb7-0247e454290d.png)

The expected behavior is not to have that underscore as parameter.

Thank you for you work :)

**Comment by steelbrain** [comment]
Hi @lgraziani2712 

While this issue is out of scope of this bridge between FlowType and Atom, I think your issue is that you are adding `void` parameter, you shouldn't be adding any parameter if the function doesn't accept it. You only have to add it to return values.

Hope that answers your question, if not feel free to discuss :)

**Comment by lgraziani2712** [comment]
Oh, thank you @steelbrain 

BTW, I think is correct to add `void` as parameter to prevent rest params to be added.

The next example has no complains:

```jsx
type HelloObject = {|
  salute: () => void,
|};
const helloObject: HelloObject = {
  salute: () => {
    console.log('Hiii');
  },
};

helloObject.salute('me');
```

This one it has:

```jsx
type HelloObject = {|
  salute: (void) => void,
//         ^ undefined
|};
const helloObject: HelloObject = {
  salute: () => {
    console.log('Hiii');
  },
};

helloObject.salute('me');
//                 ^ string. This type is incompatible with the expected param type of
```

Link: https://flow.org/try/#0C4TwDgpgBAEhA28D2B5ARgKwgY2AOSQGEkBbMeAQwEsA7KAXigG8AfAKCigGcL4BXYBABcUABQBKBgD4oANyRUAJgBo2LAL4BuNtiQ0uwKAAsEydFlwFiZSrRFxEqTDnxFS5anUZMO3XgOExSXoZH05OXX0keAgAOmQAc1EAchgqdOTxbU51VS02NhNHcxcrd1saWJ5+QRSSCEztNlBIWFMnC0Nvdk5qgJFReSVgmSGVNXzIg2N2ktx7WedcBmZfPsEBkdXwqCnouMSUtIys31y2fMLFzqr-WuT6xqA

You know where I can report this?

**Comment by steelbrain** [comment]
I'll try to handle this here, if it doesn't work. We'll open an issue in the flowtype repo

**Comment by steelbrain** [comment]
Heads up, starting from Flow v0.46.0, flow complains if you call a function with more than specified parameters.

See https://flow.org/blog/2017/05/07/Strict-Function-Call-Arity/

**Comment by lgraziani2712** [comment]
That's what I was going to link just right now haha.

I tested it and it works.

**Comment by lgraziani2712** [comment]
No more void-as-parameter thing :)
