### ISSUE TITLE
Process exited with no-zero code

### ISSUE THREAD

**Issue by lloiser** [steelbrain/flow-ide#87]
I regularly get the following errors in the dev console while writing flow code:
```
Uncaught Error: write EPIPE
  exports._errnoException @ util.js:1026
  afterWrite @ net.js:795
```

```
[exec] Process exited with no-zero code
  (anonymous function) @ index.js:58 (= ~/.atom/packages/flow-ide/node_modules/sb-exec/lib/index.js)
  emitTwo @ events.js:106
  emit @ events.js:191
  maybeClose @ internal/child_process.js:877
  (anonymous function) @ internal/child_process.js:334
  emitOne @ events.js:96
  emit @ events.js:188
  _handle.close @ net.js:493
```

Sometimes I only get the `Process exited` but most of the time I get both errors in the above order.
It seems that neither of them causes any problems while writing flow code.
Maybe this is not a big problem and maybe even "expected", but it feels wrong to pollute the dev console with errors whereas they are not really errors.

*Versions:*
``` 
MacOSX 10.11.6

Atom    : 1.16.0
Electron: 1.3.13
Chrome  : 52.0.2743.82
Node    : 6.5.0

apm  1.16.1
npm  3.10.5
node 6.9.5 x64
python 2.7.10
git 2.10.1

flow-ide 1.4.2
flow 0.44.1
```

*flow-ide settings:*
executable path = ""
only active when .flowconfig exists [x]

**Comment by steelbrain** [comment]
Thank you so much for the detailed bug description @lloiser
Does this error occur in a particular project for you or everywhere? Can you create a small isolated piece of code that throws this error reliably?

Thanks!

**Comment by lloiser** [comment]
It seems that it only happens on my project which is fairly large. (I cannot share it with you though)
I will have a closer look, maybe it's a combination of my large project, a slow machine and some other things...

**Comment by steelbrain** [comment]
Yeah currently we have a sixty seconds timeout, I'll look into increasing it :)

**Comment by lloiser** [comment]
I'm pretty sure that sixty seconds is enough, this is definitely not the problem on my side.
Maybe it's the fact that constantly writing flow code "spams" the flow server too much...

**Comment by lloiser** [comment]
After some days of testing it seems that the `Error: write EPIPE` seems to happen only for my project.

I can reproduce `Process exited with no-zero code` fairly easy:
* Checkout https://github.com/steelbrain/linter-ui-default
* prepare environment (`npm i`, install `flow-ide` in atom)
* open [lib/index.js:59](https://github.com/steelbrain/linter-ui-default/blob/v1.6.0/lib/index.js#L59)
* hit and keep `ctrl-space` pressed.
* 🔥  the developer console is filling up with error `[exec] Process exited with no-zero code`

**Comment by steelbrain** [comment]
Am able to repro with latest update, will fix today

**Comment by lloiser** [comment]
BTW: this happens on both MacOSX and Windows 10
