### ISSUE TITLE
Implement get-def of flow v0.46.0

### ISSUE THREAD

**Issue by steelbrain** [steelbrain/flow-ide#88]
This gives very accurate jump to definition, even across files. FINALLY

**Comment by leos** [comment]
I was thinking of hacking on this. Were you planning to do this as a Hyperclick provider? It looks like the npm package is 2 years out of date from the nuclide/github version :-/

**Comment by steelbrain** [comment]
Yeah Hyperclick is not really maintained, We have [`declarations`](https://atom.io/packages/declarations) package tho not a lot of people know about it 😛

**Comment by leos** [comment]
I pinged @zertosh about it earlier today and he updated hyperclick in NPM with the latest version. Would you still recommend using `declarations` instead?

**Comment by steelbrain** [comment]
I am maintaining `declarations` myself so I can fix any bugs or respond to any queries quickly. I would definitely recommend an actively maintained package over an occasionally maintained one. As an example provider, you can have a look at [`declarations-js`](https://atom.io/packages/declarations-js). It works great for declarations within file but we could replace it's jumping-to-source function to use result of flow get-def

**Comment by leos** [comment]
@steelbrain - this can be closed.
