### ISSUE TITLE
Uncovered code

### ISSUE THREAD

**Issue by lifeiscontent** [steelbrain/flow-ide#92]
Hey there, first off, awesome project. Thanks for the hard work.

Just started using flow-ide and for some reason with this code I'm getting 2 errors for both functions saying that its uncovered code.

```js
type VisibleAction = {
  type: 'workspace/commandPalette/VISIBLE', payload: { visible: boolean }
}

export const hideCommandPalette = (): VisibleAction => ({
  type: 'workspace/commandPalette/VISIBLE',
  payload: { visible: false },
});

export const showCommandPalette = (): VisibleAction => ({
  type: 'workspace/commandPalette/VISIBLE',
  payload: { visible: true },
});
```

**Comment by steelbrain** [comment]
Hi @lifeiscontent

This package gets it's coverage data from the flow CLI so if you are seeing code marked as uncovered or another bug like that, it's highly likely that it's a bug in the flow CLI itself.

I just tested your snippet on Flow v0.46.0 with this package and it shows the code as `100%` covered for me. Can you try with this flow version and see if it fixes the issue for you?

**Comment by lifeiscontent** [comment]
@steelbrain ah, yeah that fixed it I was using v0.47.0

**Comment by lifeiscontent** [comment]
Looks like they have a few new things coming out in this release: https://flow.org/blog/2017/05/07/Strict-Function-Call-Arity/

**Comment by steelbrain** [comment]
Woo! Can't wait 😄 

Closing as the issue seems to be resolved
