### ISSUE TITLE
nested files don't get read properly with flow-ide

### ISSUE THREAD

**Issue by lifeiscontent** [steelbrain/flow-ide#93]
I think I found a bug with flow-ide where if you have types that are being created from other files nested more than 1 level deep flow-ide begins to read the values as any and flow itself says there are no errors. I can create an example app if you would like me to demonstrate.

**Comment by lifeiscontent** [comment]
@steelbrain I'm guessing you will get a notification, but just in case it doesn't notify you, I've created a repo that is listed in the reference above :)

**Comment by steelbrain** [comment]
Will test and report back tonight 👍

**Comment by lloiser** [comment]
very simple: add `/* @flow */` or `// @flow` at the beginning of your files

**Comment by lloiser** [comment]
fyi: https://flow.org/en/docs/usage/#toc-prepare-your-code-for-flow

**Comment by lifeiscontent** [comment]
@lloiser thank you! that was it. Sorry, I was doing some late night coding.
