### ISSUE TITLE
Any way to ignore un-annotated arguments of exported classes/functions?

### ISSUE THREAD

**Issue by josephrocca** [steelbrain/flow-ide#98]
If we write this:

```javascript
export function multiply(a, b) {
  return a*b;
}
```

Then flow will complain that `a` and `b` aren't annotated. The reason is explained [here](https://github.com/facebook/flow/issues/1694) (basically: "Flow is stricter for any exported modules in order to avoid hard-to-find issues or bugs across different files.").

It'd be cool if I could use this flow plugin just for type inference (without annotation - basically just for smarter linting), but because of this thing with `export`, it doesn't look like it's possible.

Have I missed anything? Doesn't look like there's an [option](https://flow.org/en/docs/config/options/) to suppress this complaint, but I am new to flow.

I figured I'd ask this question here and not in facebook/flow because I doubt they would care about using flow just as a "smarter linter" like this - but maybe I am wrong, so of course feel free to close if it's not relevant to this project.

Thanks!

**Comment by steelbrain** [comment]
Hi @josephrocca 

To get only type inference you could remove the flow pragma (`// @flow`) from the files, though I would personally heavily recommend against it.

It's not really that hard to go full flow :)
For the example you mentioned you could just do

```
export function multiply(a: number, b: number): number {
  return a * b
}
```

This would increase the flow coverage when you do throughout project and help you catch many bugs before they reach production.

Alternatively you could just use the `Linter: Disable Linter` command and select Flow IDE from the list, please note that this way Flow IDE will stay disabled through projects until you enable it again with `Linter: Enable Linter`.

**Comment by josephrocca** [comment]
Thanks for your thoughts! And thanks for your work on all these Atom packages :+1: You're probably right - was mainly trying to avoid the need for a compile step on tiny js projects/experiments (i.e. goal was to pimp my editor rather than my codebase). Maybe also I'm just lazy and scared of new notation :P

It seems that if I remove `// @flow` then I don't get any sort of type errors for this sort of thing:
```
export function multiply(a,b) {
  return a*b;
}
multiply("d","a");
```
Maybe I misunderstood?

**Comment by steelbrain** [comment]
You can't have linting issues while not having a flow pragma, You will have to add a compilation step sooner or later, if you use babel for transpilation you can just add a strip types plugin to it and it should be fine

**Comment by josephrocca** [comment]
Thanks for your help! :)
